#ifndef PORTS_H_
#define PORTS_H_

// Laptop USB
#define PORT_JOYSTICK_OPERATOR 0
#define PORT_JOYSTICK_DRIVE 1
#define PORT_JOYSTICK_TURN 2


// Pulse With Modulation
#define PORT_DRIVETRAIN_TALON_LEFT 0
#define PORT_DRIVETRAIN_TALON_RIGHT 0

#define PORT_LIFTER_TALON_1 0
#define PORT_LIFTER_TALON_2 0

#define PORT_ARM_SOLENOID_A 0
#define PORT_ARM_SOLENOID_B 0


// Digital Input/Output
#define PORT_DRIVETRAIN_ENCODER_LEFT_A 0
#define PORT_DRIVETRAIN_ENCODER_LEFT_B 0
#define PORT_DRIVETRAIN_ENCODER_RIGHT_A 0
#define PORT_DRIVETRAIN_ENCODER_RIGHT_B 0

#define PORT_LIFTER_ENCODER_A 0
#define PORT_LIFTER_ENCODER_B 0
#define PORT_LIFTER_HALLFX_TOP 0
#define PORT_LIFTER_HALLFX_BOTTOM 0

// Analog Input
#define PORT_GYROSCOPE 0

#endif /* PORTS_H_ */
