#ifndef PORTS_H_
#define PORTS_H_

// Laptop USB
#define PORT_JOYSTICK_OPERATOR 0
#define PORT_JOYSTICK_DRIVE 1
#define PORT_JOYSTICK_TURN 2


// Pulse Width Modulation
#define PORT_DRIVETRAIN_TALON_LEFT_1 3
#define PORT_DRIVETRAIN_TALON_LEFT_2 0
#define PORT_DRIVETRAIN_TALON_RIGHT_1 1
#define PORT_DRIVETRAIN_TALON_RIGHT_2 2

#define PORT_LIFTER_VICTOR_1 8
#define PORT_LIFTER_VICTOR_2 9


// Digital Input/Output
#define PORT_DRIVETRAIN_ENCODER_LEFT_A 0
#define PORT_DRIVETRAIN_ENCODER_LEFT_B 1
#define PORT_DRIVETRAIN_ENCODER_RIGHT_A 2
#define PORT_DRIVETRAIN_ENCODER_RIGHT_B 3

#define PORT_LIFTER_ENCODER_A 9
#define PORT_LIFTER_ENCODER_B 8
#define PORT_LIFTER_HALL_EFFECT_TOP 4
#define PORT_LIFTER_HALL_EFFECT_BOTTOM 5

// Analog Input
#define PORT_GYROSCOPE 0
#define PORT_LIFTER_HALL_EFFECT_ANALOG_TOP 2
#define PORT_LIFTER_HALL_EFFECT_ANALOG_BOTTOM 3

#endif /* PORTS_H_ */
