#ifndef PORTS_H_
#define PORTS_H_

// Laptop USB
#define PORT_JOYSTICK_OPERATOR 0
#define PORT_JOYSTICK_DRIVE 1
#define PORT_JOYSTICK_TURN 2


// Pulse Width Modulation
#define PORT_DRIVETRAIN_TALON_LEFT_1 0
#define PORT_DRIVETRAIN_TALON_LEFT_2 1
#define PORT_DRIVETRAIN_TALON_RIGHT_1 2
#define PORT_DRIVETRAIN_TALON_RIGHT_2 3

#define PORT_LIFTER_TALON_1 4
#define PORT_LIFTER_TALON_2 5

#define PORT_ARM_SOLENOID_A 6
#define PORT_ARM_SOLENOID_B 7


// Digital Input/Output
#define PORT_DRIVETRAIN_ENCODER_LEFT_A 0
#define PORT_DRIVETRAIN_ENCODER_LEFT_B 1
#define PORT_DRIVETRAIN_ENCODER_RIGHT_A 2
#define PORT_DRIVETRAIN_ENCODER_RIGHT_B 3

#define PORT_LIFTER_ENCODER_A 4
#define PORT_LIFTER_ENCODER_B 5
#define PORT_LIFTER_HALL_EFFECT_TOP 8
#define PORT_LIFTER_HALL_EFFECT_BOTTOM 9

// Analog Input
#define PORT_GYROSCOPE 1

#endif /* PORTS_H_ */
